name: compile shaders

runs:
  using: 'composite'
  steps:
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: setup SPIRV tools
      # consider install-vulkan-sdk instead
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.204.0
        vulkan-components: Glslang, SPIRV-Cross
        vulkan-use-cache: true

    - name: install DXC
      uses: napokue/setup-dxc@v1.0.0

    - name: run shader compilers
      run: ninja
      shell: pwsh
      working-directory: piet-gpu/shader
