[package]
name = "piet-gpu-hal"
version = "0.1.0"
authors = ["Raph Levien <raph.levien@gmail.com>"]
description = "An abstraction layer for running compute kernels on GPU."
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
ash = "0.31"
ash-window = "0.5"
raw-window-handle = "0.3"
bitflags = "1.2.1"

[target.'cfg(target_os="macos")'.dependencies]
metal = "0.22"
objc = "0.2.4"
block = "0.1.6"
