[package]
name = "piet-scene"
version = "0.1.0"
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.7.2", features = ["derive"] }
smallvec = "1.8.0"
moscato = { git = "https://github.com/dfrg/pinot" }
kurbo = { version = "0.8.3", optional = true }
